### ISSUE TITLE
cannot find layout.jade

### ISSUE THREAD

**Issue by speedinghzl** [iamjohnnyzhuang/eternity#1]
非常感谢你的分享！
我在根目录下运行` node app.js` 后在浏览器中打开网页时遇到了一个错误

ENOENT: no such file or directory, open '/root/eternity/views/layout.jade'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.readFileSync (fs.js:508:33)
    at Parser.parseExtends (/root/eternity/node_modules/jade/lib/parser.js:509:18)
    at Parser.parseExpr (/root/eternity/node_modules/jade/lib/parser.js:221:21)
    at Parser.parse (/root/eternity/node_modules/jade/lib/parser.js:122:25)
    at parse (/root/eternity/node_modules/jade/lib/index.js:104:21)
    at Object.exports.compile (/root/eternity/node_modules/jade/lib/index.js:205:16)
    at handleTemplateCache (/root/eternity/node_modules/jade/lib/index.js:174:25)
    at Object.exports.renderFile (/root/eternity/node_modules/jade/lib/index.js:380:10)

非常期待你的帮助！谢谢

**Comment by iamjohnnyzhuang** [comment]
文件存放目录不正确。  /root/eternity/views/.. 这个是我放在服务器上的地址，你在本机跑吧？ 应该把地址切换成你自己本机的地址。

**Comment by speedinghzl** [comment]
嗯嗯，谢谢回复。我是在服务器上跑的不是本机，/root/eternity/views/是我服务器上的路径。
项目中view目录下的确没有layout.jade文件。请问是不是没有上传。

**Comment by iamjohnnyzhuang** [comment]
不小心传了一行不存在的代码已删除，亲测程序可以跑了。
PULL下更新。
THANKS
